export const messages = {
  en: {
    welcomeMessage: "Welcome to Your Vue.js App",
    guide:
      "For a guide and recipes on how to configure / customize this project, check out the",
    vueCliDocumentation: "vue-cli documentation",
    installedCliPlugins: "Installed CLI Plugins",
    babel: "babel",
    essentialLinks: "Essential Links",
    coreDocs: "Core Docs",
    forum: "Forum",
    communityChat: "Community Chat",
    twitter: "Twitter",
    news: "News",
    ecosystem: "Ecosystem",
    vueRouter: "vue-router",
    vuex: "vuex",
    vueDevtools: "vue-devtools",
    vueLoader: "vue-loader",
    awesomeVue: "awesome-vue",
  },
  es: {
    welcomeMessage: "Bienvenido a Tu App Vue.js",
    guide:
      "Para una guía y recetas sobre cómo configurar / personalizar este proyecto, consulta el",
    vueCliDocumentation: "documento de vue-cli",
    installedCliPlugins: "Plugins CLI Instalados",
    babel: "babel",
    essentialLinks: "Enlaces Esenciales",
    coreDocs: "Documentos Principales",
    forum: "Foro",
    communityChat: "Chat de la Comunidad",
    twitter: "Twitter",
    news: "Noticias",
    ecosystem: "Ecosistema",
    vueRouter: "vue-router",
    vuex: "vuex",
    vueDevtools: "vue-devtools",
    vueLoader: "vue-loader",
    awesomeVue: "awesome-vue",
  },
};
